### ISSUE TITLE
Error executing get loops()

### ISSUE THREAD

**Issue by richardmpan** [js2264/HiCool#1]
Dr. Serizay,

When I execute getloops() on objects imported by HiCExperiment from .mcool, I get the following error.

`Ctrl <- import("Ctrl.mcool", format = 'mcool', resolution = 160000)`
` refocus(Ctrl, "2:11002807-12093193") %>%
  zoom(10000) %>%
  HiCool::getLoops()`

PackagesNotFoundError: The following packages are not available from current channels:

  - samtools=1.16.1
  - bowtie2=2.5.0

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/bioconda/win-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

Error: one or more Python packages failed to install [error code 1]

How can I solve it? My platform is Window.

Thank you.

**Comment by js2264** [comment]
Hi @richardmpan, 
Unfortunately `getLoops()` function is not supported on Windows machines, as it relies on a `basilisk` environment itself currently not supported on Windows. This is an oversight on our part, we should have included an error message for this incompatibility. 
An alternative would be to use the Docker image we provide, granted you have Docker installed, you can initiate it with:

```
docker pull ghcr.io/js2264/ohca:bioc_RELEASE_3_17
```

I'll ping you in the future if we start supporting Windows machines.
